# Generated by Django 5.0.7 on 2024-07-12 03:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('item', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('chassi', models.CharField(max_length=45)),
                ('color', models.CharField(max_length=25)),
                ('year', models.CharField(max_length=4)),
                ('fuel_type', models.CharField(max_length=25)),
                ('cambium', models.CharField(max_length=30)),
                ('protected', models.BooleanField(default=False)),
                ('car_body', models.CharField(max_length=30)),
                ('km', models.CharField(max_length=15)),
                ('itens_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.item')),
            ],
        ),
    ]
