# Generated by Django 5.0.7 on 2024-07-14 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='chassi',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='itens_id',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='car_model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='items',
            field=models.ManyToManyField(related_name='vehicles', to='vehicle.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
