# Generated by Django 5.0.7 on 2024-07-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_remove_vehicle_chassi_remove_vehicle_itens_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='cambium',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(choices=[('Chevrolet', 'Chevrolet'), ('Fiat', 'Fiat'), ('Volkswagen', 'Volkswagen'), ('Ford', 'Ford'), ('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Renault', 'Renault'), ('Nissan', 'Nissan'), ('Jeep', 'Jeep'), ('Peugeot', 'Peugeot'), ('Citroën', 'Citroën'), ('Kia', 'Kia'), ('Mitsubishi', 'Mitsubishi'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Volvo', 'Volvo'), ('Land Rover', 'Land Rover'), ('Jaguar', 'Jaguar'), ('Mini', 'Mini'), ('Chery', 'Chery'), ('JAC Motors', 'JAC Motors'), ('Suzuki', 'Suzuki'), ('Subaru', 'Subaru'), ('Porsche', 'Porsche'), ('Lexus', 'Lexus'), ('Ram', 'Ram'), ('Tesla', 'Tesla')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Semi-Automatic', 'Semi-Automatic'), ('CVT (Continuously Variable Transmission)', 'CVT (Continuously Variable Transmission)'), ('Dual-Clutch', 'Dual-Clutch'), ('Tiptronic', 'Tiptronic'), ('DSG (Direct Shift Gearbox)', 'DSG (Direct Shift Gearbox)'), ('AMT (Automated Manual Transmission)', 'AMT (Automated Manual Transmission)'), ('SMG (Sequential Manual Gearbox)', 'SMG (Sequential Manual Gearbox)'), ('Hydramatic', 'Hydramatic'), ('Powershift', 'Powershift')], default=('Manual', 'Manual'), max_length=40),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_model',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Crossover', 'Crossover'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon'), ('Minivan', 'Minivan'), ('Pickup Truck', 'Pickup Truck'), ('Van', 'Van'), ('Roadster', 'Roadster'), ('Sportscar', 'Sportscar'), ('Luxury Car', 'Luxury Car'), ('Electric Car', 'Electric Car'), ('Hybrid Car', 'Hybrid Car'), ('Compact Car', 'Compact Car'), ('Subcompact Car', 'Subcompact Car'), ('Off-Road Vehicle', 'Off-Road Vehicle'), ('Microcar', 'Microcar'), ('Muscle Car', 'Muscle Car'), ('Supercar', 'Supercar'), ('Cabriolet', 'Cabriolet'), ('Fastback', 'Fastback'), ('Liftback', 'Liftback'), ('Targa', 'Targa')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Ethanol', 'Ethanol'), ('Flex (Gasoline/Ethanol)', 'Flex (Gasoline/Ethanol)'), ('CNG (Compressed Natural Gas)', 'CNG (Compressed Natural Gas)'), ('LPG (Liquefied Petroleum Gas)', 'LPG (Liquefied Petroleum Gas)'), ('Electric', 'Electric'), ('Hybrid (Gasoline/Electric)', 'Hybrid (Gasoline/Electric)'), ('Hybrid (Diesel/Electric)', 'Hybrid (Diesel/Electric)'), ('Biodiesel', 'Biodiesel'), ('Hydrogen', 'Hydrogen'), ('Methanol', 'Methanol'), ('Propane', 'Propane')], default=('Gasoline', 'Gasoline'), max_length=30),
        ),
    ]
