# Generated by Django 5.0.7 on 2024-07-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_remove_vehicle_cambium_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='car_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_model',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Crossover', 'Crossover'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon'), ('Minivan', 'Minivan'), ('Pickup Truck', 'Pickup Truck'), ('Van', 'Van'), ('Roadster', 'Roadster'), ('Sportscar', 'Sportscar'), ('Luxury Car', 'Luxury Car'), ('Electric Car', 'Electric Car'), ('Hybrid Car', 'Hybrid Car'), ('Compact Car', 'Compact Car'), ('Subcompact Car', 'Subcompact Car'), ('Off-Road Vehicle', 'Off-Road Vehicle'), ('Microcar', 'Microcar'), ('Muscle Car', 'Muscle Car'), ('Supercar', 'Supercar'), ('Cabriolet', 'Cabriolet'), ('Fastback', 'Fastback'), ('Liftback', 'Liftback'), ('Targa', 'Targa')], default='', max_length=20),
        ),
    ]
