# Generated by Django 5.0.7 on 2024-07-14 23:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_vehicle_car_name_alter_vehicle_car_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='car_body',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
