# Generated by Django 5.0.7 on 2024-07-14 19:57

import src.post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_images_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=src.post.models.post_image_upload_to),
        ),
    ]
