# Generated by Django 5.0.7 on 2024-07-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
    ]
