# Generated by Django 5.0.7 on 2024-07-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_rename_user_id_post_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_email',
            new_name='user',
        ),
    ]
