CAR_BRANDS = [
        ("Chevrolet", "Chevrolet"),
        ("Fiat", "Fiat"),
        ("Volkswagen", "Volkswagen"),
        ("Ford", "Ford"),
        ("Toyota", "Toyota"),
        ("Honda", "Honda"),
        ("Hyundai", "Hyundai"),
        ("Renault", "Renault"),
        ("Nissan", "Nissan"),
        ("Jeep", "Jeep"),
        ("Peugeot", "Peugeot"),
        ("Citroën", "Citroën"),
        ("Kia", "Kia"),
        ("Mitsubishi", "Mitsubishi"),
        ("BMW", "BMW"),
        ("Mercedes-Benz", "Mercedes-Benz"),
        ("Audi", "Audi"),
        ("Volvo", "Volvo"),
        ("Land Rover", "Land Rover"),
        ("Jaguar", "Jaguar"),
        ("Mini", "Mini"),
        ("Chery", "Chery"),
        ("JAC Motors", "JAC Motors"),
        ("Suzuki", "Suzuki"),
        ("Subaru", "Subaru"),
        ("Porsche", "Porsche"),
        ("Lexus", "Lexus"),
        ("Ram", "Ram"),
        ("Tesla", "Tesla")
    ]

CAR_MODELS = [
        ("Sedan", "Sedan"),
        ("Hatchback", "Hatchback"),
        ("SUV", "SUV"),
        ("Crossover", "Crossover"),
        ("Coupe", "Coupe"),
        ("Convertible", "Convertible"),
        ("Wagon", "Wagon"),
        ("Minivan", "Minivan"),
        ("Pickup Truck", "Pickup Truck"),
        ("Van", "Van"),
        ("Roadster", "Roadster"),
        ("Sportscar", "Sportscar"),
        ("Luxury Car", "Luxury Car"),
        ("Electric Car", "Electric Car"),
        ("Hybrid Car", "Hybrid Car"),
        ("Compact Car", "Compact Car"),
        ("Subcompact Car", "Subcompact Car"),
        ("Off-Road Vehicle", "Off-Road Vehicle"),
        ("Microcar", "Microcar"),
        ("Muscle Car", "Muscle Car"),
        ("Supercar", "Supercar"),
        ("Cabriolet", "Cabriolet"),
        ("Fastback", "Fastback"),
        ("Liftback", "Liftback"),
        ("Targa", "Targa")
    ]

FUEL_TYPES = [
        ("Gasoline", "Gasoline"),
        ("Diesel", "Diesel"),
        ("Ethanol", "Ethanol"),
        ("Flex (Gasoline/Ethanol)", "Flex (Gasoline/Ethanol)"),
        ("CNG (Compressed Natural Gas)", "CNG (Compressed Natural Gas)"),
        ("LPG (Liquefied Petroleum Gas)", "LPG (Liquefied Petroleum Gas)"),
        ("Electric", "Electric"),
        ("Hybrid (Gasoline/Electric)", "Hybrid (Gasoline/Electric)"),
        ("Hybrid (Diesel/Electric)", "Hybrid (Diesel/Electric)"),
        ("Biodiesel", "Biodiesel"),
        ("Hydrogen", "Hydrogen"),
        ("Methanol", "Methanol"),
        ("Propane", "Propane")
    ]

TRANSMISSION_TYPES = [
        ("Manual", "Manual"),
        ("Automatic", "Automatic"),
        ("Semi-Automatic", "Semi-Automatic"),
        ("CVT (Continuously Variable Transmission)", "CVT (Continuously Variable Transmission)"),
        ("Dual-Clutch", "Dual-Clutch"),
        ("Tiptronic", "Tiptronic"),
        ("DSG (Direct Shift Gearbox)", "DSG (Direct Shift Gearbox)"),
        ("AMT (Automated Manual Transmission)", "AMT (Automated Manual Transmission)"),
        ("SMG (Sequential Manual Gearbox)", "SMG (Sequential Manual Gearbox)"),
        ("Hydramatic", "Hydramatic"),
        ("Powershift", "Powershift")
    ]