# Generated by Django 5.0.7 on 2024-07-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_first_name_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='zipcode'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='username'),
        ),
    ]
