# Generated by Django 5.0.7 on 2024-07-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='zipcode'),
        ),
    ]
