# Generated by Django 5.0.7 on 2024-07-14 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
    ]
